### ISSUE TITLE
Deletes are not processed properly

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo-camel#65]
fcrepo-camel does not seem to be processing deletes properly. It appears to be trying to retrieve the F4 representation of the deleted item after it has been deleted, and then throwing an FcrepoOperationFailedException on the HTTP 410 response. To reproduce:

`curl -X PUT -H "Content-Type: text/turtle" --data-binary "@object.rdf" "http://localhost:8080/fedora/rest/indexableObject"`

object.rdf:

    PREFIX dc: <http://purl.org/dc/elements/1.1/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX indexing: <http://fedora.info/definitions/v4/indexing#>
 
    <> indexing:hasIndexingTransformation "default"; rdf:type indexing:Indexable; dc:title "Test"

`curl http://localhost:8983/solr/collection1/update?commit=true`

`curl -X DELETE http://localhost:8080/fedora/rest/indexableObject`

Output from fcrepo-camel:

[- JmsConsumer[fedora_indexing]] DefaultErrorHandler            ERROR Failed delivery for (MessageId: ID:springbok.local-55102-1429555066018-3:1:1:1:4 on ExchangeId: ID-springbok-mshome-net-54307-1429553996902-0-13). Exhausted after delivery attempt: 1 caught: org.fcrepo.camel.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fedora/rest/indexableObject with statusCode: 410 and message: Gone

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[fedora-to-solr    ] [fedora-to-solr    ] [activemq://fedora_indexing                                                    ] [        15]
[fedora-to-solr    ] [to1               ] [fcrepo:localhost:8080/fedora/rest                                             ] [        15]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-springbok-mshome-net-54307-1429553996902-0-13
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID:springbok.local-55102-1429555066018-3:1:1:1:4, CamelRedelivered=false, CamelRedeliveryCounter=0, JMSCorrelationID=null, JMSDeliveryMode=2, JMSDestination=queue://fedora_indexing, JMSExpiration=0, JMSMessageID=ID:springbok.local-55102-1429555066018-3:1:1:1:4, JMSPriority=4, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1429555371813, JMSType=null, JMSXGroupID=null, JMSXUserID=null, org.fcrepo.jms.baseURL=http://localhost:8080/fedora/rest, org.fcrepo.jms.eventType=http://fedora.info/definitions/v4/repository#NODE_REMOVED, org.fcrepo.jms.identifier=/indexableObject, org.fcrepo.jms.properties=, org.fcrepo.jms.timestamp=1429555371809}
	BodyType            null
	Body                [Body is null]
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.fcrepo.camel.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fedora/rest/indexableObject with statusCode: 410 and message: Gone
	at org.fcrepo.camel.FcrepoClient.head(FcrepoClient.java:96)
	at org.fcrepo.camel.FcrepoProducer.getMetadataUri(FcrepoProducer.java:149)
	at org.fcrepo.camel.FcrepoProducer.doRequest(FcrepoProducer.java:134)
	at org.fcrepo.camel.FcrepoProducer.process(FcrepoProducer.java:95)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:120)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[- JmsConsumer[fedora_indexing]] EndpointMessageListener        WARN  Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - org.fcrepo.camel.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fedora/rest/indexableObject with statusCode: 410 and message: Gone]
org.apache.camel.RuntimeCamelException: org.fcrepo.camel.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fedora/rest/indexableObject with statusCode: 410 and message: Gone
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1364)
	at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:186)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:107)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1101)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1093)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:990)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.fcrepo.camel.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fedora/rest/indexableObject with statusCode: 410 and message: Gone
	at org.fcrepo.camel.FcrepoClient.head(FcrepoClient.java:96)
	at org.fcrepo.camel.FcrepoProducer.getMetadataUri(FcrepoProducer.java:149)
	at org.fcrepo.camel.FcrepoProducer.doRequest(FcrepoProducer.java:134)
	at org.fcrepo.camel.FcrepoProducer.process(FcrepoProducer.java:95)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:120)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103)
	... 11 more

**Comment by acoburn** [comment]
@adolski can you say something about the route you're using for this?

**Comment by adolski** [comment]
@acoburn There is one route in the camelContext of my applicationContext.xml:

    <route id="fedora-to-solr">
        <from uri="activemq:fedora_indexing"/>
        <to uri="fcrepo:localhost:8080/fedora/rest"/>
        <filter>
            <xpath>
                /rdf:RDF/rdf:Description/rdf:type[@rdf:resource='http://fedora.info/definitions/v4/indexing#Indexable']
            </xpath>
            <to uri="fcrepo:localhost:8080/fedora/rest?transform=default"/>
            <to uri="http4:localhost:8983/solr/collection1/update"/>
        </filter>
    </route>

**Comment by acoburn** [comment]
@adolski you'll need to do an initial filter on the `eventType`. Any time you encounter a `http://fedora.info/definitions/v4/repository#NODE_REMOVED`, you should expect the response from fedora to be a 410.

If I were you, I'd put in a filter before sending messages to the activemq:fedora_indexing queue:

    from("activemq:topic:fedora")
        .choice()
            .when(header("org.fcrepo.jms.eventType").isEqualTo("http://fedora.info/definitions/v4/repository#NODE_REMOVED"))
                .to("activemq:queue:delete")
            .otherwise()
                .to("activemq:queue:fedora_indexing");

Or add that `choice()` block directly to the `fedora-to-solr` route.

There's an example here: https://github.com/fcrepo4/fcrepo-camel/blob/master/examples/fcrepo-camel-osgi/src/main/java/org/fcrepo/camel/examples/osgi/EventRouter.java#L44

Let me know if you need assistance translating that to the Spring DSL.

**Comment by ajs6f** [comment]
@acoburn Do we have a recipe to which we could point to help with this kind of issue? I have a sneaking suspicion that as we advertise event-driven workflows with Camel as the solution toolkit for indexing-ish workflows, this "what to do with a removal" issue will again arise.

**Comment by ajs6f** [comment]
@acoburn Never mind-- I just realized that your OSGi example is perfectly usable outside of OSGi-- sorry,

**Comment by acoburn** [comment]
There's also a fairly ugly looking example here: https://wiki.duraspace.org/display/FEDORA40/Setup+Camel+Message+Integrations

Though it would bear being more explicit about `DELETE` events.

**Comment by acoburn** [comment]
The best thing, though, would be to update the examples listed on **this README** so that they're not incorrect.
